[package]
name = "solana-heartbeat"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
hostname = "0.4"
byteorder = "1.5"
humantime = "2.1"
chrono = { version = "0.4", features = ["clock"] }
